/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DecentralizedBank } from "./DecentralizedBank";
export * as factories from "./factories";
export { DecentralizedBank__factory } from "./factories/DecentralizedBank__factory";
